### ISSUE TITLE
DB ERD

### ISSUE THREAD

**Issue by hojae-lee** [hojae-lee/Gam#2]
![image](https://user-images.githubusercontent.com/55069045/83345977-a4c1d180-a353-11ea-9e96-efc5ca1102a8.png)

**Comment by hojae-lee** [comment]
설계 - @HwangSeulKi @DongukHan @zizi2717 @hojae-lee 
ER - @HwangSeulKi  @zizi2717

**Comment by HwangSeulKi** [comment]
![GAM 프로젝트 ERD](https://user-images.githubusercontent.com/26733959/84586859-c2b02b80-ae55-11ea-9f5e-e163c9bfe1b5.png)

**Comment by hojae-lee** [comment]
@HwangSeulKi 멋지시네여;;
